### ISSUE TITLE
Is there a way to use some kind of locale?

### ISSUE THREAD

**Issue by mtellezj** [PanagiotisGeorgiadis/Elm-DatePicker#9]
Hi, I need to add support for spanish, is that possible? In Mexico the week start on monday, how can I do that? Thanks in advance.

**Comment by PanagiotisGeorgiadis** [comment]
Hello @mtellezj and thanks for raising that issue!

Adding `I18n` support has been in my TODOs for quite sometime but never proceeded with it cause I wasn't sure if anyone would use it! 😄

I'll raise a PR for it and tag you so that you can take a look at the API and discuss! 😄

**Comment by iwtilma** [comment]
Hi @PanagiotisGeorgiadis,
for me it would be great to use your DatePicker in Dutch!

**Comment by PanagiotisGeorgiadis** [comment]
I've raised https://github.com/PanagiotisGeorgiadis/Elm-DatePicker/pull/10 which adds support for `i18n` on the date picker.

I'll merge this over the weekend ( and update the [examples repo](https://github.com/PanagiotisGeorgiadis/Elm-DatePicker-examples) ) so people can use it 😄 

@mtellezj @iwtilma let me know what you think 😄

P.S. To be frank, I am not 100% pleased by this approach but with any different approach I'd have to rewrite the Date-Picker 😔

**Comment by PanagiotisGeorgiadis** [comment]
Implemented by #10

**Comment by mtellezj** [comment]
@PanagiotisGeorgiadis thanks for adding `i18n` support, it works great!. Just to follow my original comment:
>> In Mexico the week start on monday...

Any toughts about this? Thanks for your help.

**Comment by PanagiotisGeorgiadis** [comment]
Hello @mtellezj, I am looking on how to implement this as the `DatePicker` had been naively implemented originally taking `Sunday` as the first day of the week, but I can totally see the need for it to be customizable!

I will raise another PR once I've got it working and tag you there 😄

**Comment by PanagiotisGeorgiadis** [comment]
Update: I've raised another PR (https://github.com/PanagiotisGeorgiadis/Elm-DatePicker/pull/11) that I will merge today adding support for customizing the `starting weekday`.

I'll also update the examples repo accordingly.

Let me know of your thoughts 😄

**Comment by PanagiotisGeorgiadis** [comment]
Published version 4.0.0, which supports the calendar weekday customization. Also updated the examples repo to showcase how that can be customized - hope that helps! 😄

**Comment by mtellezj** [comment]
@PanagiotisGeorgiadis Thank you very much. Works like a charm!
